
OPENAI_API_KEY=""
GEMINI_API_KEY=""
ANTHROPIC_API_KEY=""
OPENAI_CLAUDE_API_KEY=""
HYPERBOLIC_LLAMA_API_KEY=""
TOGETHER_API_KEY=""
DATADOG_API_KEY=""
GROK_API_KEY=""

# FIREBASE KEYS
FIREBASE_API_KEY=""
FIREBASE_AUTH_DOMAIN=""
FIREBASE_PROJECT_ID=""
FIREBASE_STORAGE_BUCKET=""
FIREBASE_MESSAGING_SENDER_ID=""
FIREBASE_APP_ID=""
FIREBASE_MEASUREMENT_ID=""
